class Assets {
  static const splashlogo = "assets/images/samplelogo.png";
  static const onboarding1 = "assets/images/onboarding_1.png";
  static const onboarding2 = "assets/images/onboarding_2.png";
  static const onboarding3 = "assets/images/onboarding_logo.png";
  static const backbutton = "assets/images/back_button.png";
  static const icFacebook = "assets/images/ic_facebook.png";
  static const icGoogle = "assets/images/ic_google.png";
  static const logoFood = "assets/images/logo 1.png";
  static const icflame = "assets/images/ic_flame.png";
  static const icMenuLabel = "assets/images/ic_menu_label.png";
  static const techcategory = "assets/images/tech_category.png";
  static const techdiscount = "assets/images/tech_discount.png";
  static const techfood1 = "assets/images/tech_food1.png";
  static const techfood2 = "assets/images/tech_food2.png";
  static const techfood3 = "assets/images/tech_food3.png";
  static const techfood4 = "assets/images/tech_food4.png";
  static const techfood5 = "assets/images/tech_food5.png";
  static const techfood6 = "assets/images/tech_food6.png";
  static const techfood7 = "assets/images/tech_food7.png";
  static const techfood8 = "assets/images/tech_food8.png";
  static const techlogo = "assets/images/tech_logo.png";
  static const star = "assets/images/star.png";
  static const home = "assets/images/Home.png";
  static const menu = "assets/images/Menu.png";
  static const saved = "assets/images/Saved.png";
  static const user = "assets/images/User.png";
  static const star3 = "assets/images/Star3.png";
  static const like = "assets/images/like.png";
  static const dislike = "assets/images/dislike.png";
  static const pfp = "assets/images/op.png";
  static const elipse = "assets/images/elipse.png";
  Assets(String techfood5);
}
